name: ruglider_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - pandas==2.2.3
  - netcdf4==1.7.2
  - numpy==2.2.2
  - xarray==2025.1.2
  - scipy==1.15.1
  - gsw==3.6.19
  - pyyaml==6.0.2
